### ISSUE TITLE
Can't connect to arm64 docker server

### ISSUE THREAD

**Issue by arteeh** [tiltedphoques/bug-feature-reports#34]
## Description

I'm trying to run the server but no matter what I try, i can't connect. I tried connecting to both my internal and public IP address.

The server runs in my home network on a RockPro64 ARM computer running Debian (unstable).To make it run ST, i added this to my compose.yaml file:

```
skyrim:
        image: tiltedphoques/st-reborn-server
        container_name: skyrim
        restart: unless-stopped
        ports:
            - 10578:10578
        volumes:
            - /home/arteeh/skyrim:/home/server/config
```

I run docker as root. User arteeh is uid 1000 and owns /home/arteeh/skyrim.

/home/arteeh/skyrim contains STServer.ini with the following contents:
```
[general]
sLogLevel=info
bConsole=true


[LiveServices]
bAnnounceServer=true


[Gameplay]
fGoldLossFactor=0
bEnablePvp=true
bEnableGreetings=true
uDifficulty=3


[ModPolicy]
bAllowMO2=true
bAllowSKSE=true
bEnableModCheck=false


[GameServer]
sPassword=**i put a password here**
sAdminPassword=
sServerName=Deviants
bPremiumMode=true
uPort=10578
```

The server has ufw set up as a firewall, and i have configured it to allow all incoming data from port 10578. I tried also creating allow rules on my client PC and disabling the Windows firewall altogether, but no results.

I have 10578 port forwarded to the server's IP. I have experience with port forwarding other games and services. I'm not interested in using Hamachi.

I tried running the server on my Windows PC (same network). Changed the port forward to my PC's internal IP. Connecting to that server worked perfectly.

`sudo docker logs skyrim` gives the following output:
```
[19:54:48] [info] Server started on port 10578
[19:54:48] [warning] ModCheck is disabled. This can lead to desync and other oddities. Make sure you know what you are doing. We may not be able to assist you if ModCheck was disabled.
> Server started, type /help for a list of commands.

[20:19:12] [info] Server started on port 10578
[20:19:12] [warning] ModCheck is disabled. This can lead to desync and other oddities. Make sure you know what you are doing. We may not be able to assist you if ModCheck was disabled.
> Server started, type /help for a list of commands.
```

The container is on and seems to run properly. It consistently uses 6.25MiB of memory and a small percentage of my CPU.

I'm not sure what to do next or what debugging steps i can take. I'm willing to set up ModCheck if you guys think that might help, but i doubt it will help connection problems.

## Steps to reproduce

1. Install and run docker + docker-compose on an ARM64 device in a home network, like the RockPRO64 or maybe a Raspberry Pi
2. Create a compose.yaml file with the contents stated above
3. Forward port 10578 to the device's IP in the home network's router settings
4. Run `sudo docker-compose up -d` with the compose.yaml file in the working directory
5. Start the game on another PC
6. Load a post-helgen saved game
7. Connect to the server's public and/or private IP address

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

The client connects to the server.

## Evidence (optional)

The client tries to connect to the server for about five seconds, and then shows a connection error.

**Comment by vp-en** [comment]
You can try the official docker-compose.yml example, just instead of building it ourselves, then using their image from the Docker Hub

so instead of
> ```
> skyrim:
>         image: tiltedphoques/st-reborn-server
>         container_name: skyrim
>         restart: unless-stopped
>         ports:
>             - 10578:10578
>         volumes:
>             - /home/arteeh/skyrim:/home/server/config
> ```

then try this:
```
  skyrim:
    container_name: skyrim
    image: tiltedphoques/st-reborn-server:latest
    ports:
      - "10578:10578/udp"
    volumes:
     - /home/arteeh/skyrim/config:/home/server/config
     - /home/arteeh/skyrim/logs:/home/server/logs
     - /home/arteeh/skyrim/Data:/home/server/Data
    restart: unless-stopped
```

The `/udp` made the difference for me personally. Might work for you too.
